import { Metadata } from "next";
import {
  LegalPageLayout,
  LegalSection,
} from "@/components/sections/legal/legal-page-layout";

export const metadata: Metadata = {
  title: "Terms of Service — Phos AI",
  description: "Terms of Service for Phos AI image editing and generation service.",
};

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="April 2, 2026">
      <LegalSection title="1. Acceptance of Terms">
        <p>
          By accessing or using the Phos AI service at phos.studio (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you must not access or use the Service. We may update these Terms from time to time, and your continued use of the Service constitutes acceptance of any changes.
        </p>
      </LegalSection>

      <LegalSection title="2. Service Description">
        <p>
          Phos AI provides AI-powered image editing, retouching, and generation tools. The Service processes user-uploaded images through third-party artificial intelligence models to produce enhanced or modified outputs. Results are generated by AI and may vary. We do not guarantee that outputs will meet your specific expectations or requirements.
        </p>
      </LegalSection>

      <LegalSection title="3. Account &amp; Eligibility">
        <ul className="list-disc pl-5 space-y-2">
          <li>You must be at least 16 years of age (or the applicable age of digital consent in your jurisdiction) to use the Service.</li>
          <li>You must provide accurate and complete information when creating an account.</li>
          <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.</li>
          <li>You must notify us immediately of any unauthorized use of your account.</li>
          <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Credits &amp; Payments">
        <ul className="list-disc pl-5 space-y-2">
          <li>The Service operates on a credit-based system. Credits are required to process images.</li>
          <li>Credits are available through monthly subscription plans or one-time purchases.</li>
          <li>All payments are processed by Polar, our Merchant of Record. By making a purchase, you agree to Polar&apos;s terms of service and payment policies.</li>
          <li>Credit pricing and allocations are subject to change. Any changes will apply to future purchases only and will not affect credits you have already purchased.</li>
          <li>Credits are non-transferable between accounts.</li>
          <li>Purchased credits (including one-time and subscription credits) do not expire unless your account is terminated for violation of these Terms.</li>
          <li>Subscription credits are allocated at the beginning of each billing cycle.</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Refund Policy">
        <ul className="list-disc pl-5 space-y-2">
          <li>Refund requests must be submitted within 14 days of purchase through the Polar customer portal or by contacting us at <a href="mailto:hbh4231@gmail.com" className="text-primary hover:underline">hbh4231@gmail.com</a>.</li>
          <li>Only unused credits are eligible for refund. Credits that have been consumed for image processing are non-refundable.</li>
          <li>Refunds are processed by Polar to the original payment method. Processing times are subject to Polar&apos;s policies and your financial institution.</li>
          <li>We reserve the right to deny refund requests in cases of suspected abuse or fraud.</li>
          <li>Promotional or bonus credits are not eligible for refund.</li>
          <li>For EU consumers: You have the right to cancel a purchase within 14 days under the EU Consumer Rights Directive. However, by using the Service to process images (consuming credits), you acknowledge that the digital service has been fully performed and the right of withdrawal no longer applies to the consumed portion.</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. User Content &amp; Intellectual Property">
        <p className="mb-3">By uploading content to the Service, you:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Represent and warrant that you own or have all necessary rights, licenses, and permissions to upload and use such content.</li>
          <li>Grant us a limited, worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and process your uploaded content solely for the purpose of providing the Service to you.</li>
          <li>Retain full ownership of your original uploaded content.</li>
          <li>Acknowledge that AI-generated outputs may not be eligible for copyright protection in all jurisdictions, and that similar outputs may be generated for other users using different inputs.</li>
        </ul>
        <p className="mt-3">
          We do not claim ownership of your content or AI-generated outputs. We do not use your uploaded images to train AI models.
        </p>
      </LegalSection>

      <LegalSection title="7. Prohibited Use">
        <p className="mb-3">You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Generate, upload, or distribute illegal, harmful, threatening, abusive, defamatory, or obscene content.</li>
          <li>Create non-consensual intimate imagery, deepfakes, or deceptive media of real individuals without their explicit permission.</li>
          <li>Infringe upon the intellectual property, privacy, or other rights of any third party.</li>
          <li>Generate content that exploits, harms, or endangers minors.</li>
          <li>Attempt to reverse-engineer, decompile, disassemble, or extract the underlying AI models or algorithms.</li>
          <li>Circumvent or manipulate usage limits, credit systems, rate limits, or security measures.</li>
          <li>Use automated tools, bots, or scrapers to access the Service without prior written authorization.</li>
          <li>Use the Service for any purpose that violates applicable local, state, national, or international law.</li>
        </ul>
        <p className="mt-3">
          We reserve the right to remove content and suspend or terminate accounts that violate these prohibitions, without prior notice or refund.
        </p>
      </LegalSection>

      <LegalSection title="8. Service Availability &amp; Modifications">
        <p>
          We strive to maintain reliable service, but do not guarantee uninterrupted, timely, or error-free operation. We reserve the right to modify, suspend, or discontinue any feature or aspect of the Service at any time. We will make reasonable efforts to provide advance notice of material changes. We are not liable for any impact resulting from service modifications, interruptions, or discontinuation.
        </p>
      </LegalSection>

      <LegalSection title="9. Disclaimer of Warranties">
        <p>
          The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. To the maximum extent permitted by applicable law, we disclaim all warranties, whether express, implied, or statutory, including implied warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement. We do not warrant that AI-generated results will be accurate, complete, error-free, or suitable for any particular use. You use the Service at your own risk.
        </p>
      </LegalSection>

      <LegalSection title="10. Limitation of Liability">
        <p>
          To the maximum extent permitted by applicable law, Phos AI and its operators, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, revenue, goodwill, or business opportunities, arising out of or in connection with your use of the Service, regardless of the theory of liability and even if advised of the possibility of such damages.
        </p>
        <p className="mt-3">
          Our total aggregate liability for any claims arising from or related to the Service shall not exceed the total amount you have paid to us in the twelve (12) months immediately preceding the event giving rise to the claim, or USD $100, whichever is greater.
        </p>
        <p className="mt-3">
          Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited under applicable law.
        </p>
      </LegalSection>

      <LegalSection title="11. Indemnification">
        <p>
          To the extent permitted by applicable law, you agree to indemnify, defend, and hold harmless Phos AI and its affiliates from any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any content you upload to the Service. This indemnification obligation does not apply where the claim arises solely from our negligence or willful misconduct.
        </p>
      </LegalSection>

      <LegalSection title="12. Termination">
        <p>
          You may stop using the Service and request account deletion at any time. We may suspend or terminate your access if you violate these Terms or if we reasonably believe your use poses a risk to the Service or other users. Upon termination for cause, any unused credits may be forfeited. Upon voluntary account deletion, unused purchased credits will remain accessible for 30 days during which you may request a refund for eligible unused credits.
        </p>
      </LegalSection>

      <LegalSection title="13. Governing Law &amp; Dispute Resolution">
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to its conflict of law principles.
        </p>
        <p className="mt-3">
          Any dispute arising from these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If the dispute cannot be resolved within 30 days, it shall be submitted to the exclusive jurisdiction of the courts of Seoul, Republic of Korea.
        </p>
        <p className="mt-3">
          If you are a consumer in the European Union, you retain the benefit of any mandatory provisions of the law of your country of residence, and you may bring legal proceedings in the courts of your country of residence. EU consumers may also use the European Commission&apos;s Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://ec.europa.eu/consumers/odr</a>.
        </p>
      </LegalSection>

      <LegalSection title="14. Severability">
        <p>
          If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect. The invalid or unenforceable provision will be modified to the minimum extent necessary to make it valid and enforceable.
        </p>
      </LegalSection>

      <LegalSection title="15. Entire Agreement">
        <p>
          These Terms, together with our Privacy Policy and any other policies referenced herein, constitute the entire agreement between you and Phos AI regarding the Service and supersede all prior agreements and understandings.
        </p>
      </LegalSection>

      <LegalSection title="16. Contact">
        <p>
          If you have any questions about these Terms, please contact us at:<br />
          <a href="mailto:hbh4231@gmail.com" className="text-primary hover:underline">hbh4231@gmail.com</a>
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
